name: flutter_media_info
description: Library for use LibMediaInfo in flutter with support for macos, windows, linux.
version: 0.0.4-dev.3
homepage: https://pcpl2lab.ovh
repository: https://github.com/pcpl2/flutterMediainfo
issue_tracker: https://github.com/pcpl2/flutterMediainfo/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FlutterMediaInfoPlugin
        ffiPlugin: true
      macos:
        pluginClass: FlutterMediaInfoPlugin
        ffiPlugin: true
      windows:
        pluginClass: FlutterMediaInfoPlugin
