name: flutter_media_info
description: Library for use LibMediaInfo in flutter with support for macos, windows, linux.
version: 0.0.2
homepage: https://pcpl2lab.ovh
repository: https://github.com/pcpl2/flutterMediainfo
issue_tracker: https://github.com/pcpl2/flutterMediainfo/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.1
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FlutterMediaInfoPlugin
      macos:
        pluginClass: FlutterMediaInfoPlugin
      windows:
        pluginClass: FlutterMediaInfoPlugin
