# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI_Build_Example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  flutter_version: "2.5.3"

jobs:
  BuildExampleLinux:
    name: Build example app for linux x64
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'stable'
          
      - name: Enable desktop support ubuntu
        run: | 
          flutter config --enable-linux-desktop
    
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.OS }}-flutter-dependencies-cache-${{ env.flutter_version }}

      - name: Patch for linux build
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev liblzma-dev clang
          sudo ldconfig
          flutter doctor

      - run: cd example && flutter packages get

      - name: Build example for linux
        run: | 
          cd example
          flutter build -v linux --release
          
      - name: Make zip file
        uses: papeloto/action-zip@v1
        with:
          files: example/build/linux/x64/release/bundle/
          dest: FlutterMediaInfo_Example_ubuntu-20.04_x64.zip

      - name: Upload generated application to the artifacts.
        uses: actions/upload-artifact@v2
        with:
          name: FlutterMediaInfo Example ubuntu
          path: FlutterMediaInfo_Example_ubuntu-20.04_x64.zip
          retention-days: 5

  BuildExampleWindows:
    name: Build example app for windows x64
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'stable'
          
      - name: Enable desktop support windows
        run: | 
          flutter config --enable-windows-desktop
    
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.OS }}-flutter-dependencies-cache-${{ env.flutter_version }}

      - run: cd example && flutter packages get

      - name: Build example for windwos
        run: | 
          cd example
          flutter build -v windows --release
          
      - name: Make zip file
        uses: papeloto/action-zip@v1
        with:
          files: FlutterApp/build/windows/runner/Release/
          dest: FlutterMediaInfo_Example_Windows_x64.zip

      - name: Upload generated application to the artifacts.
        uses: actions/upload-artifact@v2
        with:
          name: FlutterMediaInfo windows
          path: FlutterMediaInfo_Example_Windows_x64.zip
          retention-days: 5