name: Make release new version.

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Api version (format: Major.Minor.HotFix, example: 1.2.12)'
        required: true

jobs:
  build_native_utils:
    uses: pcpl2/flutterMediainfo/.github/workflows/BuildNatives.yml@dev

  build:
    runs-on: ubuntu-latest
    needs: build_native_utils
    container:
      image:  google/dart:latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.1.0

    - name: Make directory for natives
      run: mkdir -p nativeUtils/libs

    - name: Get grpc generated files
      uses: actions/download-artifact@v3.0.1
      with:
        name: natives.zip
        path: ./nativeUtils/libs

    - name: Setup credentials
      run: | 
        mkdir -p ~/.pub-cache 
        cat <<EOF > ~/.pub-cache/credentials.json
        {
          "accessToken": "${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}",
          "refreshToken": "${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}",
          "tokenEndpoint": "${{ secrets.PUB_DEV_PUBLISH_TOKEN_ENDPOINT }}",
          "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
          "expiration": ${{ secrets.PUB_DEV_PUBLISH_EXPIRATION }},
        }
        EOF
    
    - name: Publish package
      run: pub publish --dry-run